Repository patha454/bdiff, pull requests merged in 2020-07, with the labels that each got.

#1 CI: Setup linting.
  .github/workflows/lint.yml
Labels: enhancement

#2 Bugfix: Don't lint /include until it exists.
  .github/workflows/lint.yml
Labels: bug

#4 Style: Remove unused params.
  src/bdiff.c
Labels: bug

#5 CI: Build bdiff.
  .github/workflows/main.yml
Labels: enhancement

#6 Documentation: Create readme.
  README.md
Labels: documentation

#7 CI: use .clang-format.
  .github/workflows/stylecheck.yml
Labels: bug

#8 Feature: Initial `struct Buffer` commit.
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/stylecheck.yml
  CMakeLists.txt
  include/buffer.h
  src/buffer.c
Labels: enhancement

#9 Feature: Create buffers from files.
  .clang-tidy
  CMakeLists.txt
  include/buffer.h
  include/file.h
  src/bdiff.c
  src/buffer.c
  src/file.c
Labels: enhancement

#10 CI: Enable MSVC warnings as errors.
  .github/workflows/build.yml
  src/bdiff.c
Labels: bug

#11 CI: Build on Windows.
  .github/workflows/build.yml
  CMakeLists.txt
  src/bdiff.c
  src/buffer.c
  src/file.c
Labels: enhancement
